# 애플리케이션 설정
spring:
  application:
    name: coupon-api
  
  # RabbitMQ 설정
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
  # 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:coupondb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  # JPA 설정  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true    # JPA 쿼리 콘솔 출력
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true                  # 쿼리에 주석 추가

  springdoc:
    api-docs:
      path: /v3/api-docs
      enabled: true
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
    show-actuator: true
        
  # H2 콘솔 설정  
  h2:
    console:
      enabled: true
      path: /h2-console
      
  # 컴포넌트 스캔 설정
  main:
    allow-bean-definition-overriding: true
      
# 서버 설정      
server:
  port: 8080
  servlet:
    context-path: /
    
# 로깅 설정  
logging:
  level:
    com.example.coupon: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework.context.annotation: DEBUG # 빈 등록 과정 로깅

    org.hibernate.SQL: DEBUG                    # SQL 쿼리 출력
    org.hibernate.type.descriptor.sql: TRACE   # 파라미터 값도 출력
    org.springframework.jdbc.core: DEBUG       # Spring JDBC 쿼리도 출력